apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickshield-backend
  labels:
    app: clickshield-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clickshield-backend
  template:                     
    metadata:
      labels:
        app: clickshield-backend
    spec:
      serviceAccountName: clickshield-backend-sa
      containers:
        - name: clickshield-backend
          image: 298350610133.dkr.ecr.us-east-1.amazonaws.com/clickshield-platform-repo:backend-86666561dfa4c2dc01fb021b6a1bc9ca509340d6
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: GOOGLE_SAFE_BROWSING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-safe-browsing-api-secret
                  key: GOOGLE_SAFE_BROWSING_API_KEY
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"