apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickshield-frontend
  labels:
    app: clickshield-frontend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: clickshield-frontend
  template:
    metadata:
      labels:
        app: clickshield-frontend
    spec:
      containers:
        - name: clickshield-frontend
          image: 298350610133.dkr.ecr.us-east-1.amazonaws.com/clickshield-platform-repo:frontend-af22cc5c75a296da36e73e1bc1f40a1eb7264d21
          ports:
            - containerPort: 80 #Nginx listens on 80
          resource:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"