name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      # Terraform Variables (TF_VAR_ prefix required!)
      TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_VPC_CIDR: ${{ secrets.VPC_CIDR }}
      TF_VAR_private_subnet_cidrs: ${{ secrets.PRIVATE_SUBNET_CIDRS }}
      TF_VAR_public_subnet_cidrs: ${{ secrets.PUBLIC_SUBNET_CIDRS }}
      TF_VAR_availability_zones: ${{ secrets.AVAILABILITY_ZONES }}
      TF_VAR_ZEROS: ${{ secrets.ZEROS }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v6

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      run: terraform fmt 
      continue-on-error: true
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Create a terraform.tfvars file with the Terraform variables defined in GitHub Secrets
    - name: Create Terraform Variables
      run: |
        cat > terraform.tfvars <<'EOF'
        AWS_REGION           = "${{ secrets.AWS_REGION }}"
        VPC_CIDR             = "${{ secrets.VPC_CIDR }}"
        private_subnet_cidrs = ${{ secrets.PRIVATE_SUBNET_CIDRS }}
        public_subnet_cidrs  = ${{ secrets.PUBLIC_SUBNET_CIDRS }}
        availability_zones   = ${{ secrets.AVAILABILITY_ZONES }}
        ZEROS                = ${{ secrets.ZEROS}}
        EOF
        
        echo "=== Generated terraform.tfvars ==="
        cat terraform.tfvars
      working-directory: ./infra/terraform

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init --reconfigure -backend-config="bucket=${{ secrets.S3_BUCKETNAME }}" -backend-config="key=${{ secrets.S3_KEY_PATH }}" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="encrypt=true"
      working-directory: ./infra/terraform

    # Validates the Terraform configuration files in a directory, and checks whether the configuration is syntactically valid and internally consistent
    - name: Terraform Validate
      id: validate
      run: terraform validate 

    - name: Verify State Access
      run: |
        echo "=== Current State Resources ==="
        terraform state list -state s3://${{ secrets.S3_BUCKETNAME }}/${{ secrets.S3_KEY_PATH }} || echo "Empty state - first run"

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan 
      working-directory: ./infra/terraform

    - name: Verify Terraform Configuration Files
      run: |
        echo "=== Terraform Files in Repository ==="
        find . -name "*.tf" -type f

    - name: Comment PR with Terraform Plan
      uses: actions/github-script@v9
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`\n
          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    # On push to "main", build or change infrastructure according to Terraform configuration files
    # - name: Terraform Apply
    # # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: terraform apply -auto-approve 
    #     env:
    #       # Terraform Variables (TF_VAR_ prefix required!)
    #       TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
    #       TF_VAR_VPC_CIDR: ${{ secrets.VPC_CIDR }}
    #       TF_VAR_private_subnet_cidrs: ${{ secrets.PRIVATE_SUBNET_CIDRS }}
    #       TF_VAR_public_subnet_cidrs: ${{ secrets.PUBLIC_SUBNET_CIDRS }}
    #       TF_VAR_availability_zones: ${{ secrets.AVAILABILITY_ZONES }}
    #       TF_VAR_ZEROS: ${{ secrets.ZEROS }}
