name: Terraform Runner

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      # Terraform Variables (TF_VAR_ prefix required!)
      TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_VPC_CIDR: ${{ secrets.VPC_CIDR }}
      TF_VAR_private_subnet_cidrs: ${{ secrets.PRIVATE_SUBNET_CIDRS }}
      TF_VAR_public_subnet_cidrs: ${{ secrets.PUBLIC_SUBNET_CIDRS }}
      TF_VAR_availability_zones: ${{ secrets.AVAILABILITY_ZONES }}
      TF_VAR_ZEROS: ${{ secrets.ZEROS }}
      TF_VAR_encrypt: ${{ secrets.ENCRYPT }}
      TF_VAR_ecr_kms_arn: ${{ secrets.ECR_KMS_ARN }}
      TF_VAR_eks_cluster_role: ${{ secrets.EKS_CLUSTER_ROLE }}
      TF_VAR_eks_node_group_role: ${{ secrets.EKS_NODE_GROUP_ROLE }}
      TF_VAR_eks_kms_arn: ${{ secrets.EKS_KMS_ARN }}
      TF_VAR_vpc_flow_logs_role: ${{ secrets.VPC_FLOW_LOGS_ROLE }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v6

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        role-to-assume: ${{ secrets.ACTIONS_IAM_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Mask AWS account ID
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "::add-mask::$ACCOUNT_ID"

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init --reconfigure -backend-config="bucket=${{ secrets.S3_BUCKETNAME }}" -backend-config="key=${{ secrets.S3_KEY_PATH }}" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="encrypt=true"
      working-directory: ./infra/terraform

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      run: terraform fmt 
      continue-on-error: true
      working-directory: ./infra/terraform

    # Validates the Terraform configuration files in a directory, and checks whether the configuration is syntactically valid and internally consistent
    - name: Terraform Validate
      id: validate
      run: terraform validate 
      working-directory: ./infra/terraform

    - name: Terraform Debug state
      run: terraform state list
      working-directory: ./infra/terraform

    - name: Terraform state rm
      id: remove
      run: |
        terraform state rm module.aws.container_services.eks_kms_arn
        terraform state rm module.aws.container_services.ecr_kms_arn
      working-directory: ./infra/terraform
    
    - name: Terraform Debug Plan
      run: terraform plan 2>&1 | grep -A2 vpc_flow_logs_role
      working-directory: ./infra/terraform

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan 
      working-directory: ./infra/terraform

    #  On push to "main", build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply -auto-approve 
      working-directory: ./infra/terraform