name: Trivy Scans

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '44 6 * * 3'

permissions:
  contents: read

jobs:
  containersec:
    permissions:
      contents: read 
      id-token: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan container image with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6 
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.ACTIONS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image (load locally, don't push yet)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.backend
          load: true                        # load into local docker, NOT push
          tags: clickshield-backend:${{ github.sha }}

      - name: Trivy scan (gate)
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'clickshield-backend:${{ github.sha }}'   # local image
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'                    # FAIL the job if vulns found
          ignore-unfixed: true              # optional: only fail on fixable vulns

      - name: Build frontend image (load locally, don't push yet)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.frontend
          load: true                        # load into local docker, NOT push
          tags: clickshield-frontend:${{ github.sha }}

      - name: Trivy scan (gate)
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'clickshield-frontend:${{ github.sha }}'   # local image
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'                    # FAIL the job if vulns found
          ignore-unfixed: true              # optional: only fail on fixable vulns

      - name: Build an image from Dockerfile
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: clickshield-platform-repo
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          docker build -f Dockerfile.backend -t $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG .
          docker build -f Dockerfile.frontend -t $REGISTRY/$REPOSITORY:frontend-$IMAGE_TAG .

      - name: Push image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: clickshield-platform-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:frontend-$IMAGE_TAG

      # - name: Run Trivy vulnerability scanner on Backend image
      #   uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: clickshield-platform-repo
      #     IMAGE_TAG: ${{ github.sha }}
      #   with:
      #     image-ref: '${{ steps.login-ecr.outputs.registry }}/clickshield-platform-repo:backend-${{ github.sha }}' #  this scans the image we just built
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL,HIGH'
      #     exit-code: '0' # ensures that the Trivy scan step does not fail even if vulnerabilities are found, so that the SARIF file can be uploaded to the GitHub Security tab in the next step
      
      # - name: Run Trivy vulnerability scanner on Frontend image
      #   uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: clickshield-platform-repo
      #     IMAGE_TAG: ${{ github.sha }}
      #   with:
      #     image-ref: '${{ steps.login-ecr.outputs.registry }}/clickshield-platform-repo:frontend-${{ github.sha }}' #  this scans the image we just built
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL,HIGH'
      #     exit-code: '0' # ensures that the Trivy scan step does not fail even if vulnerabilities are found, so that the SARIF file can be uploaded to the GitHub Security tab in the next step
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always() # ensures that the SARIF file is uploaded even if the Trivy scan fails (e.g. if vulnerabilities are found)
        with:
          sarif_file: 'trivy-results.sarif'

  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.0
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3 # Uploads the SARIF file to GitHub Security tab
        with:
          sarif_file: tfsec.sarif
